### ISSUE TITLE
redis database failed to create

### ISSUE THREAD

**Issue by wangzheng422** [rh-aiservices-bu/llm-on-openshift#19]
Hi,

I am trying this demo on openshift 4.13.15, when I try to create redis database using this

```yaml
apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: my-doc
spec:
  memorySize: 4GB
  modulesList:
    - name: search
      version: 2.8.4
  persistence: snapshotEvery12Hour
  replication: true
  tlsMode: disabled
  type: redis
```
I got error:
```
Error from server: error when creating "/home/3node//tmp/redis-db.yaml": admission webhook "redisenterprise.admission.redislabs" denied the request: cluster missing this module: search version: 2.8.4
```

The Redis Enterprise Operator version installed : 7.2.4-7.0 provided by Redis

I also create a route to the redis management UI, and find out there is no module loaded. 
![image](https://github.com/rh-aiservices-bu/llm-on-openshift/assets/3355135/581e4e47-e317-4dc3-993f-9144d1e1ca61)

But I can see the modules is under /opt/persistent after login into rec-0 pod
```bash
[3node@ocp4-helper ~]$ oc exec -n llm-demo rec-0 -- ls persistent/modules
Defaulted container "redis-enterprise-node" out of: redis-enterprise-node, bootstrapper
ReJSON
bf
graph
redisgears_2
search
timeseries
```

I also try to upload the module using the management UI, but the module fail to import.

Could you please help to point out what to troubleshoot next step?

Regards,
George
